config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'main/index'
  get 'signin/signin'
  post 'signin/create'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :people do
    collection do
      get 'new_person_user'
      post 'create_person_user'
    end
  end
  devise_for :users
  resources :users, only: [:edit]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root "main#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    if user.roles.exists?(name: 'admin')
      can :manage, :all
    elsif user.roles.exists?(name: 'editor')
      can :read, :all
      can :create, :all
      can :update, :all
    else
      can :read, :all
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/configuration.rb
class Configuration < ApplicationRecord
  validates :singleton_guard, uniqueness: true, if: -> { singleton_guard }
  has_one_attached :image

  def self.instance
    Configuration.first || Configuration.create(singleton_guard: true)
  end
end

app/models/labor_license.rb
# frozen_string_literal: true

class LaborLicense < ApplicationRecord
  belongs_to :person
  belongs_to :labor_license_type
end

app/models/labor_license_type.rb
# frozen_string_literal: true

class LaborLicenseType < ApplicationRecord
end

app/models/person.rb
# frozen_string_literal: true

class Person < ApplicationRecord
  belongs_to :user
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :document_number, presence: true
  validates :birth_date, presence: true
  validates :phone_number, presence: true
  validates :email, presence: true

  has_many :attendances

  def to_s
    "#{first_name} #{last_name} - #{document_number}"
  end
end

app/models/role.rb
# frozen_string_literal: true

class Role < ApplicationRecord
  has_and_belongs_to_many :users
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/roles_user.rb
# frozen_string_literal: true

class RolesUser < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/models/signin.rb
# frozen_string_literal: true

class Signin < ApplicationRecord
  belongs_to :person

  def self.signin_types
    %w[Entrada Salida]
  end

  validates :signin_type, presence: true, inclusion: { in: signin_types }
  validates :time, presence: true

  def to_s
    "#{person} - #{signin_type} - #{time}"
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_and_belongs_to_many :roles

  def has_role?(role)
    roles.exists?(name: role)
  end

  def to_s
    email
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/people_controller.rb
# frozen_string_literal: true

class PeopleController < ApplicationController
  before_action :set_person, only: %i[show edit update destroy]

  # GET /people or /people.json
  def index
    @people = Person.all
  end

  # GET /people/1 or /people/1.json
  def show; end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit; end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to person_url(@person), notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  def new_person_user
    @person = Person.new
  end

  def create_person_user
    @person = Person.new(person_params)
    @user = User.new(email: @person.email, password: @person.document_number.to_s, password_confirmation: @person.document_number.to_s)
    @user.save!
    @person.user = @user
    respond_to do |format|
      if @person.save
        flash[:success] = 'La nueva persona fue agregada al sistema correctamente'
        format.html { redirect_to signin_signin_path, notice: 'La nueva persona fue agregada al sistema correctamente' }
        format.json { render :show, status: :created, location: @person }
      else
        flash[:error] = 'Error al agregar la nueva persona al sistema'
        format.html { redirect_to signin_signin_path, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to person_url(@person), notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy!

    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_person
    @person = Person.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def person_params
    params.require(:person).permit(:first_name, :last_name, :document_type, :document_number, :birth_date,
                                   :phone_number, :email, :address, :city, :state, :zip_code, :country, :user_id)
  end
end

app/controllers/signin_controller.rb
class SigninController < ApplicationController
  def signin
    @signins = Signin.limit(20).order(time: :desc)

  end
  def create
    @signins = Signin.limit(20).order(time: :desc)
    @person = Person.find_by(document_number: params[:documento])
    if @person
      @signin_type = Signin.where(person_id: @person.id, time: Date.today.beginning_of_day..Date.today.end_of_day).count % 2 == 0 ? 'Entrada' : 'Salida'
      @signin = Signin.new(person_id: @person.id, signin_type: @signin_type, time: Time.now)
      # flash[:success] = "Se ha registrado la #{@signin_type} con éxito."
      # redirect_to signin_signin_path
    else
      flash[:error] = "No se encontró la persona con el número de documento proporcionado. le pedimos que se registre en el botón de verde de registrarme."
      #redirect_to signin_signin_path
    end

    respond_to do |format|
      if @signin && @signin.save
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@signin, partial: "signins/signin", locals: { signin: @signin }) }
        flash[:success] = "Se ha registrado la #{@signin_type} con éxito."

      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@signin, partial: "signins/form", locals: { signin: @signin }) }
        flash[:error] = "No se encontró la persona con el número de documento proporcionado. le pedimos que se registre en el botón de verde de registrarme."
      end
      format.html { redirect_to signin_signin_path, notice: "Signin was successfully created." }
    end

  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/people_helper.rb
# frozen_string_literal: true

module PeopleHelper
end

app/helpers/signin_helper.rb
module SigninHelper
end

app/views/layouts/application.html.erb
<%= stylesheet_link_tag 'application', media: 'all' %>
<%= javascript_importmap_tags 'application' %>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"><%= Configuration.instance.name %></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="<%= signin_signin_path %>"><%= t('views.signin') %></a>
        </li>
        <li class="nav-item">
          <%# <a class="nav-link" href="#">Enlace 2</a> %>
        </li>
        <!-- Agrega más enlaces aquí según sea necesario -->
      </ul>
    </div>
    <% if user_signed_in? %>
      <span>Bienvenido, <%= current_user.email %></span>
      <%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class: 'nav-link' %>
    <% else %>
      <%= link_to 'Iniciar sesión', new_user_session_path, class: 'nav-link' %>
      <%= link_to 'Registrarse', new_user_registration_path, class: 'nav-link' %>
    <% end %>

  </div>
</nav>
<% if flash[:error] %>
  <div class="alert alert-danger">
    <%= flash[:error] %>
  </div>
<% end %>
<% if flash[:success] %>
  <div class="alert alert-success">
    <%= flash[:success] %>
  </div>
<% end %>

<%= yield %>

app/views/people/_form.html.erb
<%= form_with(model: person, html: { style: "color: blue" }) do |form| %>
  <% if person.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div style="color: blue">
    <%= form_with(model: person) do |form| %>
      <div>
        <%= form.label :first_name, style: "display: block" %>
        <%= form.text_field :first_name %>
      </div>

      <div>
        <%= form.label :last_name, style: "display: block" %>
        <%= form.text_field :last_name %>
      </div>

      <div>
        <%= form.label :document_type, style: "display: block" %>
        <%= form.text_field :document_type %>
      </div>

      <div>
        <%= form.label :document_number, style: "display: block" %>
        <%= form.number_field :document_number %>
      </div>

      <div>
        <%= form.label :birth_date, style: "display: block" %>
        <%= form.date_field :birth_date %>
      </div>

      <div>
        <%= form.label :phone_number, style: "display: block" %>
        <%= form.text_field :phone_number %>
      </div>

      <div>
        <%= form.label :email, style: "display: block" %>
        <%= form.text_field :email %>
      </div>

      <div>
        <%= form.label :address, style: "display: block" %>
        <%= form.text_field :address %>
      </div>

      <div>
        <%= form.label :city, style: "display: block" %>
        <%= form.text_field :city %>
      </div>

      <div>
        <%= form.label :state, style: "display: block" %>
        <%= form.text_field :state %>
      </div>

      <div>
        <%= form.label :zip_code, style: "display: block" %>
        <%= form.text_field :zip_code %>
      </div>

      <div>
        <%= form.label :country, style: "display: block" %>
        <%= form.text_field :country %>
      </div>

      <div>
        <%= form.label :user_id, style: "display: block" %>
        <%= form.text_field :user_id %>
      </div>

      <div>
        <%= form.submit %>
      </div>
    <% end %>
  </div>

app/views/people/_person.html.erb
<div id="<%= dom_id person %>">
  <p>
    <strong>First name:</strong>
    <%= person.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= person.last_name %>
  </p>

  <p>
    <strong>Document type:</strong>
    <%= person.document_type %>
  </p>

  <p>
    <strong>Document number:</strong>
    <%= person.document_number %>
  </p>

  <p>
    <strong>Birth date:</strong>
    <%= person.birth_date %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= person.phone_number %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= person.email %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= person.address %>
  </p>

  <p>
    <strong>City:</strong>
    <%= person.city %>
  </p>

  <p>
    <strong>State:</strong>
    <%= person.state %>
  </p>

  <p>
    <strong>Zip code:</strong>
    <%= person.zip_code %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= person.country %>
  </p>

  <p>
    <strong>User:</strong>
    <%= person.user_id %>
  </p>

</div>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render "form", person: @person %>

<br>

<div>
  <%= link_to "Show this person", @person %> |
  <%= link_to "Back to people", people_path %>
</div>

app/views/people/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>People</h1>

<div id="people">
  <% @people.each do |person| %>
    <%= render person %>
    <p>
      <%= link_to "Show this person", person %>
    </p>
  <% end %>
</div>

<%= link_to "New person", new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render "form", person: @person %>

<br>

<div>
  <%= link_to "Back to people", people_path %>
</div>

app/views/people/new_person_user.html.erb
<%= form_with(model: @person, url: create_person_user_people_path, method: :post, html: { style: "color: blue; margin: 0 auto; max-width: 400px;" }) do |form| %>
    <% if @person.errors.any? %>
        <div style="color: red">
            <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

            <ul>
                <% person.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div style="color: blue">
        <div>
            <%= form.label "Nombres", style:  "mt-3" %>
            <%= form.text_field :first_name, class: "form-control", required: true %>
        </div>

        <div>
            <%= form.label "Apellidos", class: "mt-3" %>
            <%= form.text_field :last_name, class: "form-control", required: true %>
        </div>

        <div>
            <%= form.label "Tipo de documento", class: "mt-3" %>
            <%= form.select :document_type, ['DNI', 'PASAPORTE', 'LI', 'LC'], class: "form-control", required: true %>
        </div>

        <div>
            <%= form.label "Número de Documento", class: "mt-3" %>
            <%= form.number_field :document_number, class: "form-control", required: true %>
        </div>

        <div>
            <%= form.label "Fecha de Nacimiento", class: "mt-3" %>
            <%= form.date_field :birth_date, class: "form-control", required: true %>
        </div>

        <div>
            <%= form.label "eMail", class: "mt-3" %>
            <%= form.email_field :email, class: "form-control", pattern: "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}", required: true %>
        </div>

        <div>
            <%= form.label "Número de teléfono", class: "mt-3" %>
            <%= form.text_field :phone_number, class: "form-control", required: true %>
        </div>

        <div class="mt-3">
            <%= form.submit class: "btn btn-primary" %>
        </div>
    </div>
<% end %>

app/views/people/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @person %>

<div>
  <%= link_to "Edit this person", edit_person_path(@person) %> |
  <%= link_to "Back to people", people_path %>

  <%= button_to "Destroy this person", @person, method: :delete %>
</div>

app/views/signin/create.turbo_stream.erb
<!-- app/views/signins/create.turbo_stream.erb -->
<%= turbo_stream.replace "scroll-box" do %>
    <%= render partial: "signins/signins", locals: { signins: @signins } %>
<% end %>

app/views/signin/signin.html.erb
<div class="container signin-form">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="d-flex justify-content-end mb-3">
        <%= link_to 'Registrarme', new_person_user_people_path, class: 'btn btn-success' %>
      </div>
      <h2 class="text-center">Fichajes</h2>
      <form action="<%= signin_create_path%>" method="post" class="form-group">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <label for="documento" class="form-label">Número de documento:</label>
        <input type="text" id="documento" name="documento" class="form-control">
        <input type="submit" value="Fichar" class="btn btn-primary mt-3">
      </form>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="scroll-box">
        <% @signins.each do |signin| %>
          <% if signin.signin_type == "Entrada" %>
            <span class="badge rounded-pill bg-primary"><%= signin %></span>
          <% elsif signin.signin_type == "Salida" %>
            <span class="badge rounded-pill bg-success"><%= signin %></span>
          <% else %>
            <p><%= signin %></p>
          <% end %>
          <br><br>
        <% end %>
      </div>
    </div>
  </div>
</div>

    

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>